### ISSUE TITLE
 Program is hanging with Linux desktop version 

### ISSUE THREAD

**Issue by pdp11gy** [nhasbun/de10nano_fpga_linux_config#1] opened 2019-06-04 08:19 UTC
Program works fine with Linux console,   Angstrom v2014.12 - Kernel.
but is hanging (blocking?) with  Linux desktop  kernel (included default kernel ):
Angstrom v2016.12 - Kernel 4.1.33-ltsi-altera.
Example:
./loadrbf
******************************************************
MSEL Pin Config..... 0xa
FPGA State.......... User Phase
cfgwdth Register.... 0x1
.....hanging......
if CTAG is connected:
 ./loadrbf
******************************************************
MSEL Pin Config..... 0xa
FPGA State.......... User Phase
cfgwdth Register.... 0x1
cdratio Register.... 0x3
axicfgen Register... 0x0
.....hanging......

**Comment by nhasbun** [comment] 2019-06-04 16:42
Going to reproduce the error first and come back later.

**Comment by nhasbun** [comment] 2019-06-10 17:34
When using Linux desktop are you launching software from graphical environment ? Graphical environment is relying on HDMI output which at the same time requires certain FPGA configurations to work (you could check the de10nano datasheets for this).

Not a linux expert but I guess that linux kernel is detecting some key system hang when you try to reconfigure the fpga and then try to reboot the system.

**Comment by nhasbun** [comment] 2020-01-19 22:20
Closing this since no more feedback given.

**Closed as completed by nhasbun** 2020-01-19 22:20 UTC
